import { StatusBar, StyleSheet } from "react-native";
import { width } from "../../../utils/Dimensions";

export const createStyles = (theme: Theme, isDark) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: "#fff" },
    coverWrapper: {
      position: "relative",
      height: 160,
      backgroundColor: "#eee",
    },
    coverWrapperimg: {
      position: "relative",
      height: 160,
      width: width,
      backgroundColor: "#eee",
    },
    coverImage: {
      width: "100%",
      height: "100%",
    },
    changeCoverBtn: {
      position: "absolute",
      top: StatusBar.currentHeight,
      right: 10,
      backgroundColor: "#fff",
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 4,
      flexDirection: "row",
      alignItems: "center",
      width: "auto",
      // paddingTop: StatusBar.currentHeight,
    },
    changeCoverText: {
      fontSize: 12,
      color: "#333",
      marginLeft: 4,
    },
    profilePicWrapper: {
      position: "absolute",
      bottom: -40,
      left: "50%",
      transform: [{ translateX: -40 }],
      borderWidth: 3,
      borderColor: "#fff",
      borderRadius: 50,
      overflow: "hidden",
    },
    profilePic: {
      width: 80,
      height: 80,
      borderRadius: 40,
    },
    changePhotoText: {
      marginTop: 50,
      textAlign: "center",
      color: isDark ? "#fff" : "#6e008b",
      fontWeight: "500",
    },
    form: {
      padding: 16,
    },
    row: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginVertical: 8,
    },
    inputBox: {
      flexDirection: "row",
      alignItems: "center",
      borderColor: "#6e008b",
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 10,
      flex: 1,
      marginHorizontal: 4,
      height: 44,
      backgroundColor: "#fff",
    },
    icon: {
      marginRight: 6,
      color: "#6e008b",
    },
    input: {
      flex: 1,
      fontSize: 14,
    },
    otpRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 12,
      marginBottom: 4,
      borderColor: "#6e008b",
      borderWidth: 1,
      borderRadius: 8,
    },
    otpBtn: {
      backgroundColor: "#d88d2c",
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
      marginLeft: 8,
    },
    otpBtnText: {
      color: "#fff",
      fontSize: 13,
      fontWeight: "bold",
    },
    otpHint: {
      fontSize: 12,
      color: "#999",
      marginTop: 4,
      marginLeft: 4,
    },
    confirmBtn: {
      backgroundColor: "#d88d2c",
      marginTop: 20,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: "center",
    },
    confirmText: {
      color: "#fff",
      fontWeight: "bold",
      fontSize: 16,
    },
    confirmHint: {
      textAlign: "center",
      fontSize: 12,
      color: "#888",
      marginTop: 4,
    },
    bottomNav: {
      flexDirection: "row",
      justifyContent: "space-around",
      paddingVertical: 12,
      backgroundColor: "#6e008b",
    },
    pencil: {
      marginTop: -20,
      alignSelf: "flex-end",
      marginRight: 10,
      backgroundColor: "white",
      padding: 6,
      borderRadius: 40,
    },
  });
